# ACME client configuration for Let's Encrypt
acme_client letsencrypt https://acme-v02.api.letsencrypt.org/directory;
# acme_client letsencrypt https://acme-staging-v02.api.letsencrypt.org/directory;


# DNS resolver is required by ACME to resolve the CAAPI
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;

upstream django {
    server web:8000;
}

# Сервер для приема HTTP соединений и обработки ACME challenge
server {
    listen 80;
    server_name greenapi.bhguyf.ru;

    acme letsencrypt;

    location = /favicon.ico { access_log off; log_not_found off; }

    # Все прочие запросы перенаправляем на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# Сервер для обработки HTTPS соединений
server {
    listen 443 ssl;
    server_name greenapi.bhguyf.ru;

    # Подключаем сертификат и ключ, полученные автоматически
    ssl_certificate     $acme_cert_letsencrypt;
    ssl_certificate_key $acme_cert_key_letsencrypt;

    # Если сертификата еще нет, разрешаем модулю ACME запросить его
    acme letsencrypt;

    client_max_body_size 100M;

    location = /favicon.ico { access_log off; log_not_found off; }

    location / {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Передаем протокол в приложение, чтобы Django знал, что это HTTPS
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Раздача статики
    location /static/ {
        alias /app/staticfiles/;
    }

    # Раздача медиа файлов
    location /media/ {
        alias /app/media/;
    }
}
